"""Copy the three worked examples out of ``results/`` into ``examples/``.

``results/`` is regenerated by every batch run and is not committed -- 113MB of
overlays is not what a reader clones a repository for. Three of its resumes are
kept anyway, because output nobody can look at is a claim rather than evidence.

They are copied rather than moved, so they stay what the pipeline actually
writes: run the batch, run this, and a clean ``git status examples/`` says the
committed examples are byte-identical to what the code produces today. That is
the same check ``results/`` used to answer, and the reason this is a copy step
and not a hand-curated directory.
"""

from __future__ import annotations

import shutil
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]

# One per ingestion track. The spread is the point: what a native PDF, a
# scanned page and a DOCX each make available is different, and the examples
# are only worth committing if they show that difference.
EXAMPLES = ("7.anomaly", "9.ocr", "11")

# The reconstruction is drawn from resume.json, so committing it would store
# the same information twice and let the two disagree.
EXCLUDED = ("debug/pass-", "-reconstruction.pdf", "-page-")


def _wanted(source: Path, root: Path) -> bool:
    relative = source.relative_to(root).as_posix()
    return not any(fragment in relative for fragment in EXCLUDED)


def refresh(project_root: Path = PROJECT_ROOT) -> int:
    """Mirror each example from ``results/`` into ``examples/``.

    The destination is emptied first: a file that stopped being produced must
    stop being committed, or the examples would accumulate artifacts no run
    makes any more and quietly stop matching the pipeline.
    """
    missing = [
        name for name in EXAMPLES if not (project_root / "results" / name).is_dir()
    ]
    if missing:
        print(
            "refresh-examples: no result for " + ", ".join(missing)
            + " -- run `uv run restruct` first",
            file=sys.stderr,
        )
        return 1

    for name in EXAMPLES:
        source_root = project_root / "results" / name
        destination_root = project_root / "examples" / name
        if destination_root.exists():
            shutil.rmtree(destination_root)
        for source in sorted(source_root.rglob("*")):
            if not source.is_file() or not _wanted(source, source_root):
                continue
            destination = destination_root / source.relative_to(source_root)
            destination.parent.mkdir(parents=True, exist_ok=True)
            shutil.copy2(source, destination)
        print(f"refreshed: examples/{name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(refresh())
